berriart_sitemap:
    path: /sitemap.xml
    defaults: { _controller: berriart_sitemap.controller:sitemap, _format: xml }
    methods: ['GET']
    requirements: 
        _format: xml

berriart_sitemap_index:
    path: /sitemapindex.xml
    defaults: { _controller: berriart_sitemap.controller:sitemapIndex, _format: xml }
    methods: ['GET']
    requirements: 
        _format: xml
